### ISSUE TITLE
sometimes needs setTimeout in frontend tests !!

### ISSUE THREAD

**Issue by bdavidxyz** [sgmap/pix-live#111]
Really icky, but won't work without :  

```
      return click($buttonRegister).then(() => {
        // XXX: really icky test, but fail sometimes if no timeout
        setTimeout(function () {
            expect(currentURL()).to.equal('/home');
            done();
        }, 300);
      });
```

**Comment by jbuget** [comment]
Est-ce que ça ne marcherait pas en utilisant le helper `andThen` d'Ember ?

https://guides.emberjs.com/v2.8.0/testing/acceptance/

**Comment by bdavidxyz** [comment]
ça sonne juste. Je vais essayer. Comme quoi, utiliser les issues, c'est pas sans issue.

**Comment by bdavidxyz** [comment]
Et... ça marche !
