### ISSUE TITLE
Impossible to scroll down in ember test...

### ISSUE THREAD

**Issue by bdavidxyz** [sgmap/pix-live#67]
What a mess. 

Stackoverflow is unable to answer http://stackoverflow.com/questions/32466326/how-to-trigger-scroll-event-in-acceptance-test

Slack did not help.

Ember core member didn't help.

**Comment by jbuget** [comment]
Je suis prêt à m'asseoir sur ce type de tests (à base de scrolling et autre questions à tiroir) qui donnent lieu à des tests plus compliqués, fragiles et coûteux qu'ils ne rapportent véritablement.

**Comment by jbuget** [comment]
Dans la mesure où on n'en a plus besoin, on peut peut-être fermer l'issue ?

**Comment by bdavidxyz** [comment]
J'ai répondu dans stackoverflow, on peut ferme l'issue
